#!/bin/bash
## For usage with the account you plan to use spreads with!
## Acutally this installs much to much and is not usecase-sensitive.
DELIVERY_DIR="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
# Setup environment
if [ -d $USER_HOME/Arbeitsfläche ]; then
 cd $USER_HOME
 mkdir Desktop
 ln -s $USER_HOME/Arbeitsfläche ${USER_HOME}/Desktop
 cd $DELIVERY_DIR
fi

cp -fr updater.sh ../
# Update packages
apt-get update || exit 1
# Install some basic tools and libraries
apt-get -y install console-common console-data locales nginx nginx-light ntp || exit 1

# Setup udev rules
echo 'ACTION=="add", SUBSYSTEM=="usb", MODE:="666"' > /etc/udev/rules.d/99-usb.rules || exit 1
sed -i -e 's/KERNEL\!="eth\*|/KERNEL\!="/' /lib/udev/rules.d/75-persistent-net-generator.rules || exit 1
rm -f /etc/udev/rules.d/70-persistent-net.rules || exit 1

# Install spreads dependencies
apt-get -y install build-essential cython libffi-dev libjpeg8-dev liblua5.1-0\
            libudev-dev libusb-1.0-0-dev libusb-dev nginx python2.7-dev\
            python-pyexiv2 python-netifaces python-pip python-yaml unzip\
            python-pyside || exit 1
wget --continue https://www.assembla.com/spaces/chdkptp/documents/aDDsvQyhOr465JacwqjQYw/download/aDDsvQyhOr465JacwqjQYw -O /tmp/chdkptp.zip || exit 1
unzip -o -d /usr/local/lib/chdkptp /tmp/chdkptp.zip || exit 1
rm -rf /tmp/chdkptp.zip || exit 1

# Get newest pip version
pip install --upgrade pip || exit 1
mv /usr/bin/pip /usr/bin/pip.old
ln -s /usr/local/bin/pip /usr/bin/pip
pip --version || exit 1

# Install CFFI
pip install cffi || exit 1

# Install spreads from GitHub
echo "## Nothing fatal here. If updating spreads."
git clone https://github.com/jbaiter/spreads.git /usr/src/spreads
cd /usr/src/spreads || exit 1
echo "## Checking for Updates."
git pull || exit 1
# https://github.com/openxc/openxc-python/issues/18
pip install --pre pyusb || exit 1
pip install -e .[web] || exit 1
python setup.py install || exit 1

# Install cython-hidapi from GitHub
pip install git+https://github.com/gbishop/cython-hidapi.git || exit 1

# Create spreads configuration directoy
mkdir -p /home/$USER/.config/spreads || exit 1
cp $DELIVERY_DIR/files/config.yaml /home/$USER/.config/spreads || exit 1
chown -R $USER /home/$USER/.config/spreads || exit 1

# install alt start script
mkdir /var/log/spreads
chmod a+rwx /var/log/spreads
cp $DELIVERY_DIR/files/usr.local.bin.startspread \
		/usr/local/bin/startspread || exit 1

# Install spreads init script
cp $DELIVERY_DIR/files/spread /etc/init.d/spread || exit 1
chmod a+x /etc/init.d/spread || exit 1

# Add spreads init script to default boot sequence
update-rc.d spread defaults || exit 1

# Install nginx configuration
cp $DELIVERY_DIR/files/nginx_default /etc/nginx/sites-enabled/default || exit 1
chmod a+x /etc/nginx/sites-enabled/default || exit 1

# Add nginx init script to default boot sequence
update-rc.d nginx defaults || exit 1
